// <auto-generated />
using System;
using AxPlantSimWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AxPlantSimWebApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251211101237_AddOrdersTable")]
    partial class AddOrdersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("AxPlantSimWebApp.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BasketCountTz")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ContainsTz")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasInvalidData")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManualPriority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaterialAmount")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OperationNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProgramTz")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReportTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("TimeRatio")
                        .HasColumnType("REAL");

                    b.Property<int>("WorkCenterGroup")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("AxPlantSimWebApp.Models.Workplace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Week1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Week2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Week3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Week4")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerList")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkplaceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkplaceList")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Workplaces");
                });
#pragma warning restore 612, 618
        }
    }
}
