// <auto-generated />
using AxPlantSimWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AxPlantSimWebApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251211093850_AddWorkplaceTable")]
    partial class AddWorkplaceTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("AxPlantSimWebApp.Models.Workplace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Week1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Week2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Week3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Week4")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerList")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkplaceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkplaceList")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Workplaces");
                });
#pragma warning restore 612, 618
        }
    }
}
